name: neubrutalism_ui
description: A Flutter UI kit packed with Neubrutalist UI components.
maintainer: Deepraj Baidya (@deepraj02)
repository: https://github.com/deepraj02/neubrutalism_ui.git
issue_tracker: https://github.com/deepraj02/neubrutalism_ui.git/issues/
version: 0.1.1

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
